name: CI

on:
  push:
  pull_request:

jobs:
  test-js:
    name: JS tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm test

  terraform-lint:
    name: Terraform lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: docker://hashicorp/terraform
        with: 
          args: fmt -check -recursive -diff
